# Generated by Django 5.1.2 on 2024-10-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=100, unique=True, verbose_name='Телефон')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_picture', verbose_name='Аватарка')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('birthday', models.DateField(verbose_name='Дата Рождения')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
