# Generated by Django 5.1.2 on 2024-11-05 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_service_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['id'], 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастеры'},
        ),
        migrations.RemoveField(
            model_name='record',
            name='category',
        ),
        migrations.RemoveField(
            model_name='record',
            name='info',
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='site_app.myuser', verbose_name='Пользователь'),
        ),
    ]
