# Generated by Django 5.1.2 on 2024-10-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_category_myuser_bonuses_master_review_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Доп. информация')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='site_app.category', verbose_name='Категория')),
                ('datetime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='site_app.schedule', verbose_name='Дата и время')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='site_app.master', verbose_name='Мастер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='site_app.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['datetime'],
            },
        ),
    ]
